# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_install:
      - git update-index --assume-unchanged environment.yml docs/source/conf.py
    post_create_environment:
      - cd docs; make proc_csv

conda:
  environment: docs/env.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# install the package in the docs/ directory
python:
  install:
    - method: pip
      path: src/supy