# Example: Output configuration with multiple frequencies
# This example shows how to save output at multiple time resolutions

model:
  control:
    tstep: 300  # 5-minute timestep
    forcing_file: "forcing_2020.txt"
    
    # Save output at multiple frequencies
    output_file:
      format: txt         # Traditional text files
      freq: [300, 3600]   # Save both 5-minute and hourly data
      groups:             # Output groups to save
        - SUEWS           # Main SUEWS output
        - DailyState      # Daily state variables
        - ESTM            # Surface temperature output
      
  physics:
    netradiationmethod: 3
    emissionsmethod: 2

sites:
  - name: "Urban_Site"
    latitude: 51.5
    longitude: -0.1
    # ... other site parameters

# This configuration will generate:
# - *_300s.txt files with 5-minute resolution data
# - *_3600s.txt files with hourly resolution data
# - Each frequency saved in separate files for the selected groups