[build-system]
requires = ["wheel", "setuptools", "oldest-supported-numpy"]


[tool.cibuildwheel]
before-build = [
    "make suews",
]

# Install system library
[tool.cibuildwheel.linux]
before-all = "yum install -y glibc-static"

[tool.cibuildwheel.macos]
before-all = 'ln -sf "$(which gfortran-10)" /usr/local/bin/gfortran'
archs = ["x86_64", "universal2", "arm64"]