[build-system]
requires = [
    "wheel",
    "setuptools<60",
    "oldest-supported-numpy",
    "setuptools-git-versioning",
    "setuptools_scm[toml]>=6.2",
]
# the recommended "build_meta" does not work with nonstop f2py and hence is commented out
# build-backend = "setuptools.build_meta"

[project]
name = "supy-driver"
dynamic = ["version"]
requires-python = ">3.9"

# [tool.setuptools-git-versioning]
# enabled = false
# template = "2022.{tag}"
# dev_template = "{tag}.post{ccount}"
# # ignore "dirty" flag when building using CI
# dirty_template = "{tag}.post{ccount}"
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/supy-driver/_version_scm.py"
root = "../.."

[tool.cibuildwheel]
# skip 32-bit and pypy builds
# skip = ["*-win32", "*-manylinux_i686", "pp*", '*-musllinux*']
# build-frontend = "pip"
before-build = ["git describe --tags --always --dirty"]

# Increase pip debugging output
build-verbosity = 0

test-requires = "pytest"
test-command = "pytest -s '{package}/supy_driver/test'"


[tool.cibuildwheel.linux]
# Install system library
before-all = ["yum install -y glibc-static", "make suews"]
archs = ["auto64"]

[tool.cibuildwheel.macos]
before-all = [
    'ln -sf "$(which gfortran-10)" /usr/local/bin/gfortran',
    "make suews",
]
build = ['cp39*']


[tool.cibuildwheel.windows]
before-all = ["make suews"]
before-build = [
    "cd {package}",
    "python -m pip install numpy",
    "python build-win-def.py",
]
archs = ["auto64"]
