# .readthedocs.yml

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    # nodejs: "10"
    python: '3.11'
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: src

formats:
  - epub
  # - pdf

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false