name: Publish JSON Schema

# Publish schema to GitHub Pages on version tags
# Schemas are NOT committed to main branch, only published at release time
on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Manual trigger for testing
    inputs:
      dry_run:
        description: 'Dry run (skip deployment)'
        type: boolean
        default: false

jobs:
  build:
    name: Build Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install gfortran
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran
          
      - name: Install SUEWS in editable mode
        run: |
          make dev
          
      - name: Export schema for GitHub Pages
        run: |
          python -m supy.data_model.schema.exporter
          echo "✓ Schema export complete"
          
      - name: List generated files
        run: |
          echo "Generated files:"
          find public -type f | head -20
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
          
      - name: Attach schema to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            public/schema/suews-config/*.json
          body: |
            ## Schema Publication
            
            Configuration schema has been published to GitHub Pages:
            - Schema URL: https://umep-dev.github.io/SUEWS/schema/suews-config/${{ env.SCHEMA_VERSION }}.json
            
            ### Usage in YAML:
            ```yaml
            schema_version: "${{ env.SCHEMA_VERSION }}"
            $schema: "https://umep-dev.github.io/SUEWS/schema/suews-config/${{ env.SCHEMA_VERSION }}.json"
            ```
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCHEMA_VERSION: "0.1"  # Will be dynamically determined in future

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.event.inputs.dry_run != 'true'
    
    # Grant permissions for Pages deployment
    permissions:
      pages: write
      id-token: write
      
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4