name: Schema Management

# HOW THIS WORKFLOW WORKS:
# ========================
#
# TRIGGER CONDITIONS:
# - Push to master: When PR merged with relevant path changes
# - Pull request: When PR contains relevant path changes  
# - Manual dispatch: Triggered from Actions tab
#
# PRODUCTION SCENARIOS (Push to master):
# ---------------------------------------
# P1. New schema version (version bumped in version.py):
#     → Generates new version file (e.g., 0.2.json)
#     → Preserves all old versions (e.g., 0.1.json)
#     → Updates registry with all versions
#     → Deploys everything to github-pages
#     → Creates PR to commit new version to repo
#
# P2. Same version, model changed:
#     → Regenerates current version with changes
#     → Preserves version history
#     → Creates PR if schema content changed
#
# P3. First deployment (no schemas exist):
#     → Generates initial schemas
#     → Creates registry from scratch
#     → Deploys and creates PR to add to repo
#
# PREVIEW SCENARIOS (Pull Request):
# ----------------------------------
# PR1. Testing data model changes:
#      → Shows how changes affect schema
#      → Preview banner added to pages
#      → Deploys to github-pages-preview
#      → Comments/updates preview URL on PR
#
# PR2. Testing new schema version:
#      → Shows new version alongside existing ones
#      → Full version history preserved in preview
#
# PR3. Testing workflow/page changes:
#      → Uses existing schemas
#      → Tests deployment logic or page styling
#      → Preview banner shows it's not production
#
# MANUAL TRIGGER SCENARIOS:
# -------------------------
# M1. Force regeneration after issues
# M2. Initial GitHub Pages setup
# M3. Recover from failed deployments
#
# KEY BEHAVIORS:
# - Schema generation is INCREMENTAL (preserves all versions)
# - Registry tracks version history and metadata
# - Deployment includes ALL schema versions
# - PRs are created only when schemas actually change
# - Preview environment is isolated from production

on:
  push:
    branches: [master]
    paths:
      - 'src/supy/data_model/**'
      - '.github/scripts/generate_schema.py'
      - '.github/workflows/schema-management.yml'
  
  pull_request:
    paths:
      - 'src/supy/data_model/**'
      - '.github/scripts/generate_schema.py'
      - '.github/workflows/schema-management.yml'
      - '.github/pages/**'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  generate-deploy:
    name: Generate and Deploy
    runs-on: ubuntu-latest
    # Run on master push OR PR
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch'
    
    # Use preview environment for PRs, production for master
    environment:
      name: ${{ github.event_name == 'pull_request' && 'github-pages-preview' || 'github-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - run: |
          python -m pip install --upgrade pip
          pip install pydantic pyyaml numpy pandas pytz timezonefinder f90nml packaging
      
      # Generate schemas (cumulative - preserves existing versions)
      - name: Generate schemas
        run: |
          echo "🔧 Generating schemas..."
          python .github/scripts/generate_schema.py
          echo "✅ Schema generation complete"
      
      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          mkdir -p _site
          
          # Copy all schemas (old + new)
          if [ -d schemas ]; then
            cp -r schemas _site/
          else
            mkdir -p _site/schemas
            echo '{"message": "No schemas yet"}' > _site/schemas/placeholder.json
          fi
          
          # Prepare index.html with conditional preview banner
          if [ -f .github/pages/index.html ]; then
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              # Add preview banner after <body> tag
              sed '/<body>/a\
              <div style="background: #ffeb3b; color: #333; padding: 10px; text-align: center; font-weight: bold; position: fixed; top: 0; left: 0; right: 0; z-index: 9999;">⚠️ PREVIEW - PR #${{ github.event.pull_request.number }} - Not Production</div>\
              <div style="height: 40px;"></div>' .github/pages/index.html > _site/index.html
              
              # Also add banner to schema index page
              if [ -f _site/schemas/suews-config/index.html ]; then
                sed -i '/<body>/a\
                <div style="background: #ffeb3b; color: #333; padding: 10px; text-align: center; font-weight: bold;">⚠️ PREVIEW - PR #${{ github.event.pull_request.number }} - Not Production</div>' \
                _site/schemas/suews-config/index.html
              fi
            else
              cp .github/pages/index.html _site/index.html
            fi
          else
            # Simple fallback
            cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>SUEWS Schema</title>
              <meta charset="utf-8">
              <meta http-equiv="refresh" content="0; url=schemas/suews-config/">
          </head>
          <body>
              <h1>SUEWS Schema</h1>
              <p>Redirecting to <a href="schemas/suews-config/">schemas</a>...</p>
          </body>
          </html>
          EOF
          fi
          
          touch _site/.nojekyll
      
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - uses: actions/deploy-pages@v4
        id: deployment
      
      # Create PR if schemas changed (master only, for version control)
      - name: Create PR for schema updates
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet schemas/; then
            BRANCH="auto/schemas-$(date +%Y%m%d-%H%M%S)"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b "$BRANCH"
            git add schemas/
            git commit -m "chore: Update schemas [auto-generated]"
            git push origin "$BRANCH"
            
            gh pr create \
              --base master \
              --head "$BRANCH" \
              --title "🤖 Update schemas" \
              --body "Auto-generated schema update. Already deployed to GitHub Pages."
          fi
      
      # Comment on PR with preview URL
      - name: Comment preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const botComment = comments.data.find(c => 
              c.user.type === 'Bot' && c.body.includes('Preview URL:')
            );
            
            const body = `🔍 **Preview Deployed**\n\nPreview URL: ${{ steps.deployment.outputs.page_url }}\n\n⚠️ This is a preview deployment. The yellow banner indicates non-production status.`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body
              });
            }