name: Schema Management

# Generates and deploys schemas when data models change
# Creates PRs for version control (required due to branch protection)

on:
  push:
    branches: [master]
    paths:
      - 'src/supy/data_model/**'
      - '.github/scripts/generate_schema.py'
      - '.github/workflows/schema-management.yml'
  
  pull_request:
    paths:
      - 'src/supy/data_model/**'
      - '.github/scripts/generate_schema.py'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  # Generate schemas and deploy immediately
  generate-deploy:
    name: Generate and Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - run: |
          python -m pip install --upgrade pip
          pip install pydantic pyyaml numpy pandas pytz timezonefinder f90nml packaging
      
      # Generate schemas
      - name: Generate schemas
        run: python .github/scripts/generate_schema.py
      
      # Deploy to GitHub Pages immediately
      - name: Deploy to Pages
        run: |
          mkdir -p _site
          cp -r schemas _site/
          [ -f .github/pages/index.html ] && cp .github/pages/index.html _site/index.html
          touch _site/.nojekyll
      
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - uses: actions/deploy-pages@v4
        id: deployment
      
      # Create PR for version control (due to branch protection)
      - name: Create PR if schemas changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet schemas/; then
            BRANCH="auto/schemas-$(date +%Y%m%d-%H%M%S)"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b "$BRANCH"
            git add schemas/
            git commit -m "chore: Update schemas [auto-generated]"
            git push origin "$BRANCH"
            
            gh pr create \
              --base master \
              --head "$BRANCH" \
              --title "🤖 Update schemas" \
              --body "Auto-generated schema update. Already deployed to GitHub Pages."
          fi

  # Validate PRs
  validate:
    name: Validate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - run: |
          python -m pip install --upgrade pip
          pip install pydantic pyyaml numpy pandas pytz timezonefinder f90nml packaging
      
      - name: Test schema generation
        run: |
          python .github/scripts/generate_schema.py
          echo "✅ Schema generation successful"